[package]
name = "logpose-core"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "1.0"
uuid = { version = "1", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
utoipa = { version = "4" }